CREATE TABLE training_tasks (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    dataset_id INTEGER,
    model_version_id INTEGER,
    model_type VARCHAR(50) NOT NULL,
    hyperparameters TEXT,
    status VARCHAR(20) DEFAULT 'pending' NOT NULL,
    progress FLOAT DEFAULT 0.0,
    current_epoch INTEGER DEFAULT 0,
    total_epochs INTEGER,
    current_step INTEGER DEFAULT 0,
    total_steps INTEGER,
    metrics TEXT,
    logs TEXT,
    error_message TEXT,
    start_time TIMESTAMPTZ,
    end_time TIMESTAMPTZ,
    duration_seconds INTEGER,
    gpu_memory_usage TEXT,
    model_path VARCHAR(500),
    created_by INTEGER,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);